### PR TITLE
Getting it to work with dependent app

### PR DESCRIPTION
**Pull request by squeevee**
**Minor changes:**

- removed composer.lock and added composer.lock to .gitignore, since composer.lock is generated from the local composer state
- moved the require statement for autoload.php to a new file bootstrap.php . My calling app has a global vendor directory generated by composer in a different location, so the require statement would fail. A dependent app without a global vendor directory could require bootstrap.php in order to consume the library. This seems more in line with convention.
- several small syntactic fixes

**Medium change:**

I've added a property 'metadataMappings' to ActivityPubConfig, and made it to be used by ActivityPubModule.

'metadataMappings' default value is null, and it expects an array of strings, each containing a path to a directory for use by Doctrine\ORM\Mapping\Driver\XmlDriver . The XmlDriver searches the directories for files with the '.dcm.xml' file extension and uses them to explicitly define the way that objects are represented in the database.

ActivityPub::updateSchema() doesn't work for me because Doctrine doesn't support tables with columns that use the ENUM data type. I'd prefer to use my app's data migrating system anyway for design harmony with other modules. It requires me to explicitly define the schema, so defining the mappings too gives me some flexibility.

### CODE REVIEW

**Comment by squeevee** [comment]
oh hang on, an extra commit got in there. I'm still getting used to git cli

**Comment by jdormit** [comment]
Thanks for the PR! Really cool to see this project attracting interest.

Can you tell me a little more about your use case for `metadataMappings`? This is my first Doctrine project (heck, it's my first PHP project in general) so I'm not super familiar with the Doctrine API. My thinking was that `updateSchema` would only create the tables required for the AP library, and callers could define their other tables however they want. Why doesn't that work in this case?

Would adding custom `metadataMappings` mean that the library caller would be response for defining the `ActivityPubObject` and `Field` entities in their XML? That sounds like it could be really brittle, although i guess if it is just an advanced option we could add some documentation around it.

Your other changes all seem great - I didn't think about the fact that a library shouldn't need to `require autoload.php` since callers will be doing that anyway. I like having an optional bootstrap folder so that we can distribute the library independent of Composer if people want that.

**Comment by squeevee** [comment]
I've never used Doctrine before either, I'm just going by what I've run into. 

When calling updateSchema, it would fail as Doctrine attempted to understand the current schema. My application is a module in a larger project (and I'd really prefer not to require a second database), so many tables are predefined including ones with the MySql enum type, which is specifically not supported by Doctrine.

I've found this just now, which suggests I could use a type mapping instead. That looks simpler so I'm going to check it out. 

https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/cookbook/mysql-enums.html

I might still favor the metadata mapping though, and yes it would be an advanced feature (though one supported by Doctrine, not this project). Maybe I'm just superstitious, but I'd prefer to explicitly define the changes that happen to my database.

**Comment by squeevee** [comment]
About mapping, for reference:

https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/basic-mapping.html

https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/xml-mapping.html

**Comment by squeevee** [comment]
So I added
```
$driverName = $entityManager->getConnection()->getDriver()->getName();
if ($driverName === 'pdo_mysql')
{
    $entityManager->getConnection()->getDatabasePlatform()
        ->registerDoctrineTypeMapping('enum', 'string');
}
```
To ActivityPub::updateSchema() as suggest by that recipe. It runs without an error. It also dropped all the other tables in my database. !

If we want to support using this library with an existing database, I'm sure we could iron out any complications that arise from automatic scheme updating. But yeah, I'd also like the option to do it manually. I think that suits me much better.

**Comment by jdormit** [comment]
> It also dropped all the other tables in my database. !

Yikes! :scream: 

Aha - from the [Doctrine API docs](https://www.doctrine-project.org/api/orm/2.6/Doctrine/ORM/Tools/SchemaTool.html#method_updateSchema):

> `void updateSchema(array $classes, boolean $saveMode = false)`
>
>    Updates the database schema of the given classes by comparing the ClassMetadata instances to the current database schema that is inspected.
>
>    `boolean` `$saveMode` If `TRUE`, only performs a partial update without dropping assets which are scheduled for deletion.

So if we update the method to this:

```php
public function updateSchema()                                        
{                                                                     
    $entityManager = $this->module->get( EntityManager::class );
    $driverName = $entityManager->getConnection()->getDriver()->getName();
    if ( $driverName === 'pdo_mysql' )
    {
        $entityManager->getConnection()->getDatabasePlatform()
            ->registerDoctrineTypeMapping('enum', 'string');
    }
    $schemaTool = new SchemaTool( $entityManager );                   
    $classes = $entityManager->getMetadataFactory()->getAllMetadata();
    $schemaTool->updateSchema( $classes, true );                      
}
```

Does that create the correct tables without deleting any other tables?

Related to allowing callers to define their own mappings - will the `ActivityPubObject` and `Field` classes still work the way they are supposed to if their mappings are moved elsewhere? The library won't work if those classes aren't hooked up properly to the database.

**Comment by jdormit** [comment]
> will the ActivityPubObject and Field classes still work the way they are supposed to if their mappings are moved elsewhere

Reading back through your original post, did I misunderstand the intent of this idea? Do you want to define the ActivityPub entities in a separate XML document, or do you want to define *other* entities that will get loaded up by Doctrine in the ActivityPub library?

If it's the second case, I'm hoping that the solution I outlined in my last comment would work better - as long as we can create and manage the entities that ActivityPub-PHP relies on without clobbering existing tables, I think we should just use Doctrine internally to manage the `objects` and `fields` tables and let callers manage their other tables however they want.

**Comment by squeevee** [comment]
https://github.com/pterotype-project/activitypub-php/pull/3#issuecomment-459147457
This change to updateSchema is able to work with the existing database without any apparent problems. However it is proving a major problem to get it to work within the context of my application, metadata mappings (which are completely optional to users of the library) seem like the cleanest solution, which is part of why I say this solution suits me.

**Comment by squeevee** [comment]
So I have realized that for my app, the migration tool I have available won't be able to do everything I need. I will unavoidably have to work around it, and so I have found a solution that I'm reasonably satisfied with. If you're really not comfortable with the metadata mappings then I'll relent.

**Comment by jdormit** [comment]
It would actually be really helpful if you tell me a little more about the migration tool you're using - especially since we will definitely need to provide migration hook-ins at some point in case the data model of the library changes in future iterations. What tool are you using, and how were you planning to hook up ActivityPub-PHP?

**Comment by jdormit** [comment]
Update here - https://github.com/pterotype-project/activitypub-php/commit/6d4e3391f4cacf7c7801ba8beb2cbb3f321fcab3 changes the `updateSchema` method to account for MySQL enum types and not deleting existing tables. Does the latest version successfully install the ActivityPub tables on your system?

**Comment by squeevee** [comment]
https://github.com/pterotype-project/activitypub-php/pull/3#issuecomment-463427237
Right, so the Flarum extension migration... tool? feature? is as I understand it based to some extent on the Laravel approach to data migration but is its own custom implementation. Essentially, I provide Flarum with an ordered set of PHP files, each one defines an incremental change to the database schema, and Flarum can use those to alter the database forwards and backwards according to whatever versioning stuff it needs to do.

The main limitation of this is that what I provide isn't so much a hook as a declarative array. I can't access the database configuration during the migration, that's all supposed to happen behind the scenes. The obvious problem re/ this library is that I therefore can't configure ActivityPub to connect to the database and do its thing. But what I didn't anticipate at first is that this also means I will be unable to populate the new schema during migration, from existing user and content data.

Flarum provides an actual proper general-purpose hook when an extension is activated, which is what I'm using now for migration. I've never known of another Flarum extension doing this, but I've also never known of another Flarum extension doing much of what ActivityPub-php is doing. So far it seems saner, more unavoidable, and less problematic than I anticipated at first.

I don't know how Laravel proper does this. I can imagine that as something this library would want to cooperate with in the way you mention. I think as far as Flarum is concerned I'll get by.

**Comment by squeevee** [comment]
> Update here - [6d4e339](https://github.com/pterotype-project/activitypub-php/commit/6d4e3391f4cacf7c7801ba8beb2cbb3f321fcab3) changes the `updateSchema` method to account for MySQL enum types and not deleting existing tables. Does the latest version successfully install the ActivityPub tables on your system?

It works, no deletions

**Comment by jdormit** [comment]
> Flarum provides an actual proper general-purpose hook when an extension is activated, which is what I'm using now for migration.

This is what I've done for Pterotype V1 as well in WordPress, and it seems like a good approach to me. At least it preserves your ability to customize and hook into the migration process however you want.

Okay, I'll go ahead and close this issue and we can continue the discussion on #4.

**Pull request closed without merging**
